### ISSUE TITLE
World (selector) listener improvement

### ISSUE THREAD

**Issue by Slachy-Dot** [ThijmenGThN/TraderNotify#17]
Multiverse / other world management plugins support 

Trader notify loops Tru all worlds
Would be best add support for custom world names eg

Config:

#Default worlds (make sure to match them with server.properties )
 Overworld: true
 Nether: false
 End: false 

#Multiverse add your world to enable trader notify 

Example_overworld: true

**Comment by ThijmenGThN** [comment]
Thank you for this request,

I was not successful in finding a way on how to get this implemented. However, I do find that this should be implemented properly.

Feel free to contribute to this project may you feel the need and have the time.

For now this will be on the lowest priority.

**Comment by ThijmenGThN** [comment]
Added the ability to change from listening only to the first world to all worlds.

More specific options might come in future versions.

Closing this thread, thank you for your feedback!
