### ISSUE TITLE
Small Improvements

### ISSUE THREAD

**Issue by Chris6ix** [ThijmenGThN/TraderNotify#29]
Hey!

I just saw your Plugin and looked through the source code a bit as I'm trying to help improve some plugins.

1.
I saw in your Utils.java that you are looking for Wandering Traders and Trader Llamas...isn't it better to just look for Wandering Traders as the plugin notifies players when a Wandering Trader is nearby and not a Trader Llama?
The current behavior could tell players that there is a Wandering Trader nearby when there is only a Trader Llama...

2.
Please remove the info from your Resource page that players should reload their Server, as this is really not a good idea!
Bukkit, Spigot or Paper Servers should NEVER be reloaded as it can cause extreme problems!
https://madelinemiller.dev/blog/problem-with-reload/

Kind Regards,
Chris6ix

btw love your extremely detailed code documentation :)

**Comment by ThijmenGThN** [comment]
Thank you for helping me to improve this plugin, I really do appreciate it! 😄 

1). You're right, I will make it so it will only seek for a wandering trader.

2). That's only for setup, but I understand that it could be misunderstood, I will change it.
   /reload-tradernotify is meant for reloading the config.
   
If you have any other suggestions, please let me know!

Thanks again!


~ Thijmen

**Comment by Chris6ix** [comment]
No problem man :)
I will let you know if I have any other suggestions

Thanks for your fast and friendly reply and keep up the good work!

**Comment by ThijmenGThN** [comment]
I appreciate the kind words 😃 

Have a wonderful day!

**Comment by Chris6ix** [comment]
You too!

**Comment by ThijmenGThN** [comment]
Requested improvements have been implemented 😄

_You can check what's changed here,
https://github.com/ThijmenGThN/TraderNotify/pull/30/commits/e50220221143655dd9a19abd6f95a02ffeb96759_
