### ISSUE TITLE
SocketTimeoutException on enable

### ISSUE THREAD

**Issue by SlimeDog** [ThijmenGThN/TraderNotify#33]
Spigot 1.17.1-3171
TraderNofify 1.6.0

On server start-up
```
[09:32:07] [Server thread/INFO]: [TraderNotify] Enabling TraderNotify v1.6.0
[09:32:07] [Server thread/INFO]: §d[TraderNotify] §fAn error has occurred: java.net.SocketTimeoutException: Connection timed out
```
This probably occurred on previous versions, as well.

Suggestions/requests:
- Since it is tagged at level INFO, it was not trapped by our error-checker. And there is no stack trace. It should be tagged as a WARN or ERROR, with a stack trace, and more informative message.
- Possibly, this is generated to an attempt to check for updates. We have our own automagical out-of-game update checker, so block outgoing network connections to (for example) raw.githubusercontent.com. Please implement a configuration option to disable update checks.

**Comment by ThijmenGThN** [comment]
Thank you for reaching out @SlimeDog,

I really do appreciate your feedback. 

Your concern is fully understood and for that reason I am willing to add an option called:
` secure: <true/false> `
This will allow for the plugin to neglect external connections made by the build in auto updater.

However, if not rule breaking, remain enabled by default. Having the plugin auto update to the most recent version prevents any breaking changes that server owners have to worry about.

Let me know what your thoughts are on this 😄

Have a delightful day!

~ Thijmen

**Comment by SlimeDog** [comment]
You are making the blasé assumption that (automatic) updates are not themselves breaking. That is not our experience, especially with MC plugins. We test every plugin release and update (on a test server) before I allow them on production servers.

BTW, the (semi-)standard configuration node is
>enable-updates: true|false

Another is
>enable-metrics: true|false

which allows bStats connections (we enable those).

**Comment by ThijmenGThN** [comment]
I'll be sure to add the following:

> enable-updates: true|false
> enable-metrics: true|false

If there's anything else I should add or change, be sure to let me know in this thread.

Thanks again for helping me improve this plugin 😄

~ Thijmen

**Comment by ThijmenGThN** [comment]
Hi again!

As you may have noticed, I've gone ahead and implemented this.
Thank  you for your continues support, I appreciate all the feedback.

Have a pleasant day!

**Comment by SlimeDog** [comment]
I did notice 😎 and the changes are very much appreciated. As discussed, I have disabled update checks, since we have our own automagical update-checker. bStats metrics are enabled.
